services:
  web:
    build: .
    container_name: realestate_web
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: realestate_db
    env_file:
      - .env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: