# Generated by Django 5.2.4 on 2025-08-03 11:30
from django.db import migrations
import os

def create_admin(apps, schema_editor):
    User = apps.get_model('realestate', 'User')
    if not User.objects.filter(is_staff=True, is_superuser=True).exists():
        User.objects.create_superuser(
            username=os.environ.get('DJANGO_ADMIN_USERNAME', 'admin'),
            email=os.environ.get('DJANGO_ADMIN_EMAIL', 'admin@example.com'),
            password=os.environ.get('DJANGO_ADMIN_PASSWORD', 'AdminPass123!')
        )


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
